apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: myapp
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: myapp-container
          image: gcr.io/sit727-23t1-hossain-e8d2586/gck-build-task:latest
          ports:
            - containerPort: 8080
